### ISSUE TITLE
After the first start can't access whatsapp anymore

### ISSUE THREAD

**Issue by felipew** [anatolinicolae/whatsapp#4]
After using it for a while, I accidentally closed the main window, after that I closed and opened the app again and then the new window present me with a screen to choose a new browser.

**Comment by contraultra** [comment]
+1
![anatolinicolae whatsapp](https://cloud.githubusercontent.com/assets/11040069/9392463/b255c366-4731-11e5-8dab-2c35dfbaa0db.png)

**Comment by JorritPosthuma** [comment]
I found out it's a problem with the Application Cache. Running this in terminal clears the cache:

```
rm -rf ~/Library/Application\ Support/WhatsApp/Application\ Cache/
```

**Comment by felipew** [comment]
Nice workaround! :) work perfectly

**Comment by anatolinicolae** [comment]
Can confirm that @JorritPosthuma solution solves the problem! I'll do some research anyway to purge the cache automatically.
